config/routes.rb
Rails.application.routes.draw do
  
  get "up" => "rails/health#show", as: :rails_health_check
  root "weathers#index"
  get 'weathers', to: 'weathers#index', as: 'weathers'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/weathers_controller.rb
class WeathersController < ApplicationController
  def index
    if params[:address].present?
      @address = params[:address]
      @weather_data = WeatherService.fetch_weather(@address)
      
      if @weather_data.nil?
        flash[:error] = "Couldn't retrieve weather data for the address."
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weather_helper.rb
module WeatherHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <%= javascript_importmap_tags %>

  </head>
  <body>
    <div class='container'>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

app/views/weathers/index.html.erb
<div class='bd-content'>
<%# Flash message for errors %>
<% if flash[:error] %>
  <div class="alert alert-danger">
    <%= flash[:error] %>
  </div>
<% end %>

<%# Form to submit the address for weather information %>
<%= form_with url: weathers_path, method: :get, class:'form' do |form| %>
  <div class="mb-3">
    <%= form.label :address, "Enter Address", class: 'form-label' %>
    <%= form.text_field :address, value: @address, class: "form-control-sm", placeholder: "Enter city or address" %>
  </div>
  <div class="mb-3 form-group">
    <%= form.submit "Get Weather", class: "btn btn-primary" %>
    <%= link_to "Clear", weathers_path , class: "btn btn-warning" %>
  </div>
<% end %>

<%# Display weather data if available %>
<% if @weather_data %>
  <div class="weather-info">
    <h3>Weather for <%= @address %></h3>
    <p><strong>Temperature:</strong> <%= @weather_data[:temperature] %> °C</p>
    <p><strong>High:</strong> <%= @weather_data[:high] %> °C</p>
    <p><strong>Low:</strong> <%= @weather_data[:low] %> °C</p>
    <p><strong>Description:</strong> <%= @weather_data[:description] %></p>
  </div>
<% end %>
</div>